// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzdzhhzielxwwlnfhavn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6ZHpoaHppZWx4d3dsbmZoYXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDQ3MDMsImV4cCI6MjA2MTIyMDcwM30.NULd413vDZJsEvrCEk4HFMZLLWAI-CqvnrV899JG_LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);